name: Build

on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Build Release Files
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: release_on_${{ matrix. os }}
#          path: release/
#          retention-days: 1

      - name: 执行上传
        uses: luochongfei/up2qn@master
        with:
          bucket: dalimeizhuang # 空间名称，按实际情况填写
          zone: 华南 # 存储区域，按实际情况填写 备注1
          access_key: QGhnCC-1gcZYITeZATAiysRZGYoJNofSrgDoO_LF # 七牛云 AccessKey 备注2
          secret_key: K_cmeVxFntWTkGDRLMUVQACnXQWIiLuEYBV98QOx # 七牛云 SecretKey 备注2
          local_dir: release # 本地文件夹
          local_exclude: "**/node_modules/**" # 要排除的内容，要符合 glob 格式
          target_dir: /exam # 要上传到七牛云中的文件夹
